name: CI

on:
  push:
    branches: [main, working]
  pull_request:

jobs:
  nix:
    name: nix build / flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check --print-build-logs
      - run: nix build --print-build-logs
